# CONFIGURACION GENERAL
server:
  port: 8084

spring:
  application:
    name: envios
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# PERFIL DE DESARROLLO (dev)
spring:
  config:
    activate:
      on-profile: dev

  # Conexion a tu base de datos Laragon (Sin tilde)
  datasource:
    url: jdbc:mysql://localhost:3306/db_envios?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true